# Generated by Django 5.2 on 2025-04-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_manager_background'),
        ('accounts', '0006_manager_background'),
    ]

    operations = [
    ]
