# Generated by Django 5.2 on 2025-05-01 01:37

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_manager_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerBackground',
        ),
    ]
