# Generated by Django 5.2 on 2025-05-01 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20250430_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerbackground',
            name='opacity',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
