# Generated by Django 5.1.3 on 2025-05-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_managerbackground_opacity'),
        ('accounts', '0008_remove_manager_background'),
    ]

    operations = [
    ]
